# main menu navigation url and icon
# 配置菜单导航的名称、路径和图标icon.
menu:
  首页:
    url: /
    icon: fa-home
  标签:
    url: /tags
    icon: fa-tags
  分类:
    url: /categories
    icon: fa-bookmark
  归档:
    url: /archives
    icon: fa-archive
  关于  :
    url: /about
    icon: fa-user-circle-o

# index page dream text,
# 配置首页显示"梦想"的语句.
dream:
  enable: ture
  text: The best preparation for tomorrow is doing your best today.

# Whether to display the title of the recommended posts
# 是否显示推荐文章的标题
recommend:
  showTitle: true

# Configure website favicon and LOGO
# 配置网站favicon和网站LOGO
favicon: /medias/favicon.png
logo: /medias/logo.png

# The configuration of the second button in the home banner,
# including the display name of the button, the font awesome icon, and the hyperlink to the button.
# 首页 banner 中的第二个按钮的配置，包括按钮的显示名称、font awesome图标和按钮的超链接.
indexbtn:
  enable: true
  name: Github
  icon: fa-github-alt
  url: https://github.com/jiangwen5945

# Whether to activate the Post TOC.
# 是否激活文章 TOC 功能.
toc:
  enable: true

# 是否激活文章末尾的打赏功能，默认激活（你替换为的你自己的微信、支付宝二维码图片、或者使用网络图片也可以）.
reward:
  enable: true
  title: 你的赏识是我前进的动力
  wechat: /medias/reward/wechat.png
  alipay: /medias/reward/alipay.jpg

# profile in about page, including avatars, career, and personal introductions.
# 在”关于”页面中配置个人信息，包括头像、职业和个人介绍.
profile:
  avatar: /medias/avatar.jpg
  career: Software Engineer
  introduction: If you wish to succeed, you should use persistence as your good friend, experience as your reference, prudence as your brother and hope as your sentry.

# config my projects informations in about page.
# If you don't want to display this `My Projects` content, you can deactivate or delete this configuration.
# 在“关于”页面配置"我的项目"信息，如果你不需要这些信息则可以将其设置为不激活或者将其删除.
myProjects:
  enable: true
  data:
    hexo-theme-matery:
      icon: fa-meetup
      iconBackground: 'linear-gradient(to bottom right, #66BB6A 0%, #81C784 100%)'
      url:  https://gitee.com/jiangwen5945/jiangwen5945/tree/dev-blog/
      desc: This is a Hexo blog theme with responsive design.
    xiamaoShop:
        icon: fa-database
        iconBackground: 'linear-gradient(to bottom right, #F06292 0%, #EF5350 100%)'
        url:  http://www.987tea.com
        desc: This is a network shopping platform with tea.
    Go:
        icon: fa-file-text-o
        iconBackground: 'linear-gradient(to bottom right, #29B6F6 0%, #1E88E5 100%)'
        desc: A website base Vue 

# config my skills informations in about page.
# If you don't want to display this `My Skills` content, you can deactivate or delete this configuration.
# 在“关于”页面配置"我的技能"信息，如果你不需要这些信息则可以将其设置为不激活或者将其删除.
mySkills:
  enable: true
  data:
    PHP:
      background: 'linear-gradient(to right, #FF0066 0%, #FF00CC 100%)'
      percent: 70%
    JavaScript:
      background: 'linear-gradient(to right, #9900FF 0%, #CC66FF 100%)'
      percent: 75%
    HTML:
      background: 'linear-gradient(to right, #2196F3 0%, #42A5F5 100%)'
      percent: 80%
    CSS:
      background: 'linear-gradient(to right, #00BCD4 0%, #80DEEA 100%)'
      percent: 85%
    Axure:
      background: 'linear-gradient(to right, #4CAF50 0%, #81C784 100%)'
      percent: 70%
    PS:
      background: 'linear-gradient(to right, #FFEB3B 0%, #FFF176 100%)'
      percent: 75%

# config gallery of my photos in about page.
# If you don't want to display this `Gallery` content, you can deactivate or delete this configuration.
# 在“关于”页面配置"我的相册"图片，如果你不需要这些信息则可以将其设置为不激活或者将其删除.
myGallery:
  enable: true
  data:
    - http://wx4.sinaimg.cn/mw690/b1bc0c45gy1fwv03ny4etj20hs0a6jv2.jpg
    - http://wx4.sinaimg.cn/mw690/b1bc0c45gy1fwv03l50sxj20z60k3ahh.jpg
    - http://wx1.sinaimg.cn/mw690/b1bc0c45gy1fwv03r4dzij20z60k3k45.jpg
    

# Whether to display post-calender in the `archive` page
# 设置在归档页面中是否显示'文章日历'控件
postCalendar: true

# the Gitalk config，default disabled
# Gitalk 评论模块的配置，默认为不激活
gitalk:
  enable: true
  owner: jiangwen5945
  repo: Gitalk
  oauth:
    clientId: 3236a6f7975a50e6643f
    clientSecret: ffe1f5524b818724876a533e005c681f4f8670c6
  admin: jiangwen5945

# the Gitment config，default disabled
# Gitment 评论模块的配置，默认为不激活
gitment:
  enable: false
  owner:
  repo:
  oauth:
    clientId:
    clientSecret:

# disqus config, default disabled
# Disqus评论模块的配置，默认为不激活
disqus:
  enable: false
  shortname:

# Livere comment configuration, the default is not activated
# Livere 来必力评论模块的配置，默认为不激活
livere:
  enable: false
  uid: MTAyMC80MDY0My8xNzE3MA

# Whether to display fork me on github icon and link, default true, You can change it to your repo address
# 配置是否在 header 中显示 fork me on github 的图标，默认为true，你可以修改为你的仓库地址.
githubLink:
  enable: true
  url: https://github.com/jiangwen5945/jiangwen5945.github.io
  title: Fork Me

# The post featured images that needs to be displayed when there is no image.
# 无文章特色图片时需要显示的文章特色图片.
featureImages: 
- /medias/featureimages/default1.jpg
- /medias/featureimages/default2.jpg
- /medias/featureimages/default3.jpg
- /medias/featureimages/default4.jpg
- /medias/featureimages/default5.jpg
- /medias/featureimages/default6.jpg
- /medias/featureimages/default7.jpg


# 背景音乐
music:
  autoplay: ''                                     # 是否自动播放[autoplay / '']
  home: /medias/music/Always With Me.mp3           # 主页背景音乐
  others:                  
    - /medias/music/The promise.mp3
    - /medias/music/canon in d.mp3
    - /medias/music/Always With Me.mp3      
  